oncotest/oncotest/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

from  django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pantum/',include("pantum.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path('api/',include("oncotest_api.urls")),
    path('api-auth/', include('rest_framework.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

oncotest/pantum/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('home/', home_page, name='home'),
    path('doctors/', all_doctors, name='doctors'),
    path('research/', Researches.as_view(), name='research'),
    path('reviews/', AddReviews.as_view(), name='reviews'),
    path('contacts/', contacts, name='contacts'),
    path('login/', LoginUser.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('profile/', Profile.as_view(), name='profile'),
    path('consultation/',AddConsultation.as_view(),name='consultation'),



]

oncotest/pantum/models.py
from django.db import models
from django.contrib.auth.models import User

SPECIALIZATION = [
    ('Гематолог', 'Врач-гематолог'),
    ('Онколог', 'Врач-онколог'),
    ('Терапев', 'Врач-терапевт'),
    ('Врач УЗД', 'Врач ультразвуковой диагностики'),
    ('Врач КДЛ', 'Врач клинико-лабораторной диагностики'),

]

RESEARCH = [
    ('Биохимический анализ крови', 'Биохимический анализ крови'),
    ('Общий анализ крови', 'Общий анализ крови'),
    ('Pantum Detect', 'Онкотест Pantum Detect'),
    ('Инструментальная диагностика', 'Инструментальная диагностика'),
    ('Цитологические исследования', 'Цитологические исследования'),
]
# class User(models.Model):
#     username = models.CharField(max_length=100, verbose_name='Имя пользователя', default="username")
#     password = models.CharField(max_length=100, verbose_name='Пароль',default="password")


# Добавить класс для авторизации и аутентификации
class Account(models.Model):
    surname = models.CharField(max_length=100, verbose_name='Фамилия')
    name = models.CharField(max_length=100, verbose_name='Имя')
    fathername = models.CharField(max_length=100, verbose_name='Отчество')
    age = models.IntegerField(verbose_name='Возраст')

    class Meta:
        abstract = True


class Doctors(Account):
    specialization = models.CharField(max_length=100, verbose_name='Специализация', choices=SPECIALIZATION)
    experience = models.IntegerField(verbose_name='Стаж работы')
    photo = models.ImageField(upload_to="photo_doctor", null=True, verbose_name='Фото')

    def __str__(self):
        return str(self.surname)

    class Meta:
        verbose_name = 'Врачи'
        verbose_name_plural = 'Врачи'

class Clients(Account):
    phone = models.CharField(max_length=40, verbose_name='Телефон')
    email = models.CharField(max_length=100, verbose_name='Email', null=True)
    city = models.CharField(max_length=100, verbose_name='Город')

    def __str__(self):
        return str(self.surname)

    class Meta:
        verbose_name = 'Клиенты'
        verbose_name_plural = 'Клиенты'


class DoctorsSpecialization(models.Model):
    name = models.CharField(max_length=100, choices=SPECIALIZATION, verbose_name='Специализация')
    doctor = models.ForeignKey("Doctors", on_delete=models.DO_NOTHING, verbose_name='Врач')

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = 'Специализация'
        verbose_name_plural = 'Специализация'



class Consultation(models.Model):
    clients = models.ForeignKey('Clients', on_delete=models.CASCADE, null=True, verbose_name='Клиент')
    service = models.CharField(max_length=100, null=True, verbose_name='Услуги')
    date = models.CharField(max_length=30, verbose_name='Дата')
    phone = models.CharField(max_length=40, verbose_name='Телефон', default="")
    def __str__(self):
        return str(self.service)

    class Meta:
        verbose_name = 'Консультации'
        verbose_name_plural = 'Консультации'


class Research(models.Model):
    name = models.CharField(max_length=30, choices=RESEARCH, verbose_name='Исследование')
    description = models.CharField(max_length=1000, null=True, verbose_name='Описание')
    photo = models.ImageField(upload_to="photo_research", null=True, verbose_name='Фото')

    def __str__(self):
        return str(self.name)

    class Meta:
        verbose_name = 'Исследования'
        verbose_name_plural = 'Исследования'


class Reviews(models.Model):
    clients = models.ForeignKey('Clients', on_delete=models.CASCADE, null=True, verbose_name='Клиент')
    rating = models.PositiveIntegerField(null=True, verbose_name='Рейтинг')
    description = models.CharField(max_length=100, verbose_name='Описание')

    def __str__(self):
        return str(self.clients)

    class Meta:
        verbose_name = 'Отзывы'
        verbose_name_plural = 'Отзывы'

class ConsultationQueue(models.Model):
    value = models.PositiveIntegerField(verbose_name='значение')

oncotest/pantum/forms.py
from django import forms
from .models import *
from django.core.validators import ValidationError
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.contrib.auth.models import User


class UserProfileForm(UserChangeForm):
    class Meta:
        model = Clients
        fields = ['surname', 'name', 'fathername', 'age', 'phone', 'email', 'city']
        widgets = {
            'surname': forms.TextInput(attrs={'placeholder': 'Фамилия'}),
            'name': forms.TextInput(attrs={'placeholder': 'Имя'}),
            'fathername': forms.TextInput(attrs={'placeholder': 'Отчество'}),
            'age': forms.TextInput(attrs={'placeholder': 'Возраст'}),
            'phone': forms.TextInput(attrs={'placeholder': 'Мобильный телефон (формат +375 ХХ ХХХ ХХ ХХ)'}),
            'email': forms.TextInput(attrs={'placeholder': 'Ваша электронная почта'}),
            'city': forms.TextInput(attrs={'placeholder': 'Город'}),
        }

class AddReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ['clients', 'rating', 'description']
        widgets = {
            'clients': forms.TextInput(attrs={'placeholder': 'Ваш ID номер..'}),
            'rating': forms.TextInput(attrs={'placeholder': 'Введите рейтинг от 0 до 5..'}),
            'description': forms.Textarea(attrs={'cols': 50, 'rows': 6})
        }

    def clean_rating(self):
        rating = self.cleaned_data['rating']
        if rating > 5:
            raise ValidationError('Введите рейтинг от 0 до 5')

        return rating

    def clean_description(self):
        description = self.cleaned_data['description']
        if len(description) > 100:
            raise ValidationError('Длина отзыва превышает 100 символов')

        return description
class ConsultationForm(forms.ModelForm):
    class Meta:
        model=Consultation
        fields=['clients','service','date','phone']
        widgets = {
            'clients': forms.TextInput(attrs={'placeholder': 'Ваш ID номер'}),
            'service': forms.TextInput(attrs={'placeholder': 'Введите услугу, на которую Вы хотели бы записаться'}),
            'date': forms.TextInput(attrs={'placeholder': 'Введите желаемую дату'}),
            'phone': forms.TextInput(attrs={'placeholder': 'Введите Ваш номер телефона'})
        }

class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Ваш логин', widget=forms.TextInput(attrs={'placeholder': 'Логин..'}))
    email = forms.EmailField(label='Ваш email', widget=forms.TextInput(attrs={'placeholder': 'Введите Ваш email..'}))
    password1 = forms.CharField(label='Пароль', widget=forms.TextInput(attrs={'placeholder': 'Введите пароль..'}))
    password2 = forms.CharField(label='Повторите пароль',
                                widget=forms.TextInput(attrs={'placeholder': 'Повторите пароль..'}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'placeholder': 'Введите логин..'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'placeholder': 'Введите пароль..'}))

oncotest/pantum/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views import View
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout,login
from .models import Doctors, Research, Reviews, Consultation
from .forms import AddReviewForm, RegisterUserForm, LoginUserForm, UserProfileForm,ConsultationForm
from .utils import *


def home_page(request):
    return render(request, "home.html")


class Researches(DataMixin, ListView):
    model = Research
    template_name = 'researches.html'
    context_object_name = "research"


def all_doctors(request):
    context = {
        "doctors": Doctors.objects.all(),
    }
    return render(request, "doctors.html", context=context)

# Личный кабинет
class Profile(DataMixin,CreateView):
    form_class = UserProfileForm
    template_name = 'profile.html'
    success_url = reverse_lazy('profile')

# Запись на консультацию
class AddConsultation(DataMixin, CreateView):
    form_class = ConsultationForm
    template_name = 'consultation.html'
    success_url = reverse_lazy ('home')



#Добавление отзыва
class AddReviews(DataMixin, CreateView):
    form_class = AddReviewForm
    template_name = 'reviews.html'
    success_url = reverse_lazy('reviews')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviews']=Reviews.objects.all()
        return context
  

def contacts(request):
    return render(request, "contacts.html")

# класс регистрации пользователя
class RegisterUser(DataMixin, CreateView):
    form_class = RegisterUserForm
    template_name = 'register.html'
    success_url = reverse_lazy('login')

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Регистрация")
        return dict(list(context.items()) + list(c_def.items()))



# функция для автоматической авторизации пользователя при успешной регистрации
    def form_valid(self, form):
        user=form.save()
        login(self.request, user)
        return redirect('home')

#класс авторизации пользователя
class LoginUser(DataMixin, LoginView):
    form_class = LoginUserForm
    template_name = 'login.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        c_def = self.get_user_context(title="Авторизация")
        return dict(list(context.items()) + list(c_def.items()))

    def get_success_url(self):
        return reverse_lazy('home')


def logout_user(request):
    logout(request)
    return redirect('login')

oncotest/pantum/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>{% block title %} {% endblock %}</title>
</head>
<body>

    {% include "navbar.html"%}

    {% block content%}
<!--    Вставляем информацию другого шаблона -->
    {% endblock %}

</body>
</html>

oncotest/pantum/templates/consultation.html
{% extends 'base.html' %}

{% block title %}consultation{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

<h1> {{title}} </h1>

<div class="container mt-3" style="width: 95%; font-size: 14px">
    <div class="card p-3 border-dark text-center" style="font-size: 18px;">
        Запись на прием к врачу, проведение исследования
    </div>
<form action="{% url 'consultation' %}" method="post">
    {{form|crispy}}
    {% csrf_token %}

<button type="submit" class="btn btn-dark">Отправить</button>
    <div class="container mt-3" style="width: 100%; font-size: 14px">
        <div class="card p-3 border-dark text-center" style="font-size: 19px;">
        Наш специалист свяжется с Вами в ближайшее время
        </div>
    </div>
</form>
</div>


{% endblock %}

oncotest/pantum/templates/contacts.html
{% extends 'base.html' %}

{% block title %}contacts{% endblock %}

{% block content %}

<section class="section-centers display">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="call-string j4 laptop-j5" align="center">
                    <table cellpadding="1" cellspacing="1" align="center">
                        <tbody>
                        <tr>
                            <td colspan="1" style="text-align: center;">
                                <b class="strong" style="color: #030303;">
                                    КОНТАКТ-ЦЕНТР</b>
                            </td>
                        </tr>
                        <tr>
                            <td style="text-align: center;">
                                <b class="strong" style="color: #030303;"> <b class="no-link"
                                >+375 (29) 777-77-77</b>
                                </b>- единый номер.
                                Eжедневно с 7:00 до 22:00
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="slide__content">
                    <br>
                    <div class="name">г. Минск, ул.Первомайская, 14</div>
                    </br>
                    <div class="box">
                        <div class="title">Call-центр(запись на прием):</div>
                        <p>
                            <b class="no-link" >+375 (29) 777-77-77 </b>
                        </p>
                    </div>


                    <div class="box">
                        <div class="title">Call-центр(городской номер):</div>
                        <p>
                            <b class="no-link" >+375 (17) 293-98-00</b>
                        </p>
                    </div>
                    <div class="box">
                        <div class="title">Время работы центра:</div>
                        <table>
                            <tbody>
                            <tr>
                                <td>ПН-ПТ:</td>
                                <td>с 07:30 до 21:00</td>
                            </tr>
                            <tr>
                                <td>Суббота:</td>
                                <td>с 08:00 до 20:00</td>
                            </tr>
                            <tr>
                                <td>Воскресенье:</td>
                                <td>с 09:00 до 16:00</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>


{% endblock %}

oncotest/pantum/templates/doctors.html
{% extends 'base.html' %}

{% block title %}doctors{% endblock %}

{% block content %}

<table class="table">
  <thead>
    <tr>
      <th scope="col">Фото</th>
      <th scope="col">Фамилия, имя, отчество </th>
      <th scope="col">Специальность</th>
      <th scope="col">Стаж работы, лет</th>
      <th scope="col">Возраст</th>
    </tr>
  </thead>
  <tbody>
    {% for doctor in doctors %}
       <tr>
          <td>{% if  doctor.photo %} <img style="max-height:100px" style="max-width:100px" src="{{ doctor.photo.url }}"/> {% endif %} </td>
          <td>{{ doctor.surname }} {{ doctor.name }} {{ doctor.fathername }}</td>
          <td>{{ doctor.get_specialization_display}}</td>
          <td>{{ doctor.experience }}</td>
          <td>{{ doctor.age }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>


{% endblock %}

oncotest/pantum/templates/home.html
{% extends 'base.html' %}

{% block title %}home{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
<main id="main ">
    <div class="container blog-page">
        <div class="row">
            <div class="col-lg-14">
                <section class="section-slider">
                    <div class="section-slider_box-text">
                        <div class="section-slider_box-text_block">
                            <h1 class="section-slider_box-text__title">Онкотест</h1>
                        </div>
                    </div>
                </section>
                <section class="section-custom section1">
                    <div class="section-custom_box">
                        <p>Рак часто прогрессирует незаметно и не проявляет себя в течение длительного времени. «PanTum Detect»
                            дает возможность начать проведение своевременной диагностики до появления дискомфорта или первых симптомов онкологического заболевания.</p>
                        <p>Тестирование PanTum Detect заключается в изучении макрофагов – подвижных клеток иммунной системы человека, способных поглощать и переваривать чужеродные
                            для организма частицы, в том числе опухолевые клетки.</p>
                        <p>Макрофаги выходят из кровеносного русла, перемещаются в ткани, поглощают специфические опухолевые структуры и мигрируют обратно в периферическую кровь.
                            Опухолевые клетки концентрируются в макрофагах, что позволяет детально исследовать их и точно определить пороговые величины индикаторов метаболических
                            процессов.</p>
                    </div>
                    <div class="section-custom_box">
                        <p>Пациенты с обоснованным подозрением на злокачественность (получение положительного результата теста PanTum Detect, выявившего превышение порогового
                            значения) направляются на дальнейшее обследование с целью подтверждения или исключения диагноза.</p>
                        <p>Тест PanTum Detect позволяет получить информацию о возможном наличии 60+ видов онкологических заболеваний на всех стадиях развития, в том числе
                            нулевой (предраковые заболевания), включая патологии, для которых в настоящее время отсутствуют эффективные методики раннего скрининга.</p>
                    </div>
                </section>
            </div>
        </div>
    </div>
</main>


{% endblock %}

oncotest/pantum/templates/login.html
{% extends 'base.html' %}

{% block title %}login{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

<h1> {{title}} </h1>

<div class="container mt-3" style="width: 95%; font-size: 14px">
    <div class="card p-3 border-dark text-center" style="font-size: 18px;">
        Вход в личный кабинет
    </div>
<form action="{% url 'login' %}" method="post">
    {{form|crispy}}
    {% csrf_token %}


    <button type="submit" class="btn btn-dark">Войти</button>
</form>
</div>


{% endblock %}

oncotest/pantum/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FFEFD5;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Pantum</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'home' %}">Главная</a>
                <a class="nav-link" href="{% url 'research' %}">Исследования</a>
                <a class="nav-link" href="{% url 'doctors' %}">Врачи</a>
                <a class="nav-link" href="{% url 'contacts' %}">Контакты</a>
                <a class="nav-link" href="{% url 'reviews' %}">Отзывы</a>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #FFEFD5;">
            <a class="btn btn-dark me-md-2" href="{% url 'consultation' %}">Онлайн-запись</a>
            {% if request.user.is_authenticated %}
                <a class="btn btn-dark me-md-2" href="{% url 'profile' %}">Личный кабинет</a> </li>
                <li class="last"> {{user.username}}
                <a class="btn btn-dark me-md-2" href="{% url 'logout' %}">Выйти</a> </li>
            {% else %}
                <a class="btn btn-dark me-md-2" href="{% url 'register' %}">Регистрация</a>
                <a class="btn btn-dark me-md-2" href="{% url 'login' %}">Войти</a>
            {% endif %}
        </nav>
    </div>
</nav>

oncotest/pantum/templates/profile.html
{% extends 'base.html' %}

{% block title %}profile{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

<h1> {{title}} </h1>
<!--<table class="table">-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th scope="col">Услуга</th>-->
<!--      <th scope="col">Дата</th>-->
<!--    </tr>-->
<!--  </thead>-->
<!--  <tbody>-->
<!--    {% for cons in consultation%}-->
<!--      <tr>-->
<!--        <td>{{ cons.service }}</td>-->
<!--        <td>{{ cons.date }}</td>-->
<!--      </tr>-->
<!--    {% endfor %}-->
<!--  </tbody>-->
<!--</table>-->
<div class="container mt-3" style="width: 95%; font-size: 14px">
    <div class="card p-3 border-dark text-center" style="font-size: 18px;">
        Профиль пользователя
    </div>
<form action="{% url 'profile' %}" method="post">
    {{form|crispy}}
    {% csrf_token %}


<button type="submit" class="btn btn-dark">Сохранить</button>
</form>
</div>


{% endblock %}

oncotest/pantum/templates/register.html
{% extends 'base.html' %}

{% block title %}register{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

<h1> {{title}} </h1>

<div class="container mt-3" style="width: 95%; font-size: 14px">
    <div class="card p-3 border-dark text-center" style="font-size: 18px;">
        Регистрация нового пользователя
    </div>
<form action="{% url 'register' %}" method="post">
    {{form|crispy}}
    {% csrf_token %}


    <button type="submit" class="btn btn-dark">Добавить</button>
</form>
</div>


{% endblock %}

oncotest/pantum/templates/researches.html
{% extends 'base.html' %}

{% block title %}researches{% endblock %}

{% block content %}
<table class="table">
  <thead>
    <tr>
      <th scope="col">Наименование исследования</th>
      <th scope="col">Описание</th>
    </tr>
  </thead>
  <tbody>
    {% for res in research%}
      <tr>
        <td>{{ res.get_name_display }}</td>
        <td>{{ res.description }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock %}

oncotest/pantum/templates/reviews.html
{% extends 'base.html' %}

{% block title %}reviews{% endblock %}

{% block content %}
{% load crispy_forms_tags %}

<h1> {{title}} </h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Клиент</th>
      <th scope="col">Рейтинг</th>
      <th scope="col">Описание</th>
    </tr>
  </thead>
  <tbody>
    {% for rev in reviews %}
      <tr>
        <td>{{ rev.clients.name }}</td>
        <td>{{ rev.rating }}</td>
        <td>{{ rev.description }}</td>
      </tr>
    {% endfor %}
  </tbody>
</table>

<div class="container mt-3" style="width: 95%; font-size: 14px">
    <div class="card p-3 border-dark text-center" style="font-size: 18px;">
        Оставьте свой отзыв
    </div>
<form action="{% url 'reviews' %}" method="post">
    {{form|crispy}}
    {% csrf_token %}


    <button type="submit" class="btn btn-dark">Добавить</button>
</form>
</div>



{% endblock %}